import { useOfficerMeQuery } from '@haveyouseen-org/network/src/generated'
import { Container } from '@haveyouseen-org/ui/src/components/atoms/Container'
import { LinkButton } from '@haveyouseen-org/ui/src/components/atoms/LinkButton'
import { AddNewCase } from '@haveyouseen-org/ui/src/components/templates/AddNewCase/AddNewCase'
import Head from 'next/head'
import { MapProvider } from 'react-map-gl'

export default function AddNewCasePage() {
  const officer = useOfficerMeQuery()

  if (!officer?.data?.officerMe) {
    return (
      <Container className="flex items-center justify-center h-96 bg-gray-50">
        <div className="p-12 space-y-2 bg-white">
          <div className="mb-4">Need officer permission.</div>
          <LinkButton href="/officer">Get permission</LinkButton>
        </div>
      </Container>
    )
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MapProvider>
          <AddNewCase />
        </MapProvider>
      </main>
    </>
  )
}
