import { Container } from '@haveyouseen-org/ui/src/components/atoms/Container'
import { IsLoggedIn } from '@haveyouseen-org/ui/src/components/organisms/IsLoggedIn'
import { IsOfficer } from '@haveyouseen-org/ui/src/components/organisms/IsOfficer'
import { AddNewCase } from '@haveyouseen-org/ui/src/components/templates/AddNewCase/AddNewCase'
import { MapProvider } from 'react-map-gl'
import Head from 'next/head'
import { FormProviderAddNewCase } from '@haveyouseen-org/forms/src/addNewCase'

export default function AddNewCasePage() {
  return (
    <>
      <Head>
        <title>Create Case | Have you seen? | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-25">
        <Container>
          <IsLoggedIn>
            <IsOfficer>
              <MapProvider>
                <FormProviderAddNewCase>
                  <AddNewCase />
                </FormProviderAddNewCase>
              </MapProvider>
            </IsOfficer>
          </IsLoggedIn>
        </Container>
      </main>
    </>
  )
}
