import Head from 'next/head'
import { About } from '@haveyouseen-org/ui/src/components/templates/About'
import { Container } from '@haveyouseen-org/ui/src/components/atoms/Container'

export default function Login() {
  return (
    <>
      <Head>
        <title>Login | Have you seen? | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-25">
        <Container>
          <About />
        </Container>
      </main>
    </>
  )
}
